### ISSUE TITLE
Add guide to invite bot to server

### ISSUE THREAD

**Issue by El-Vim55** [janaSunrise/overflow-discord-bot#64]
I'm not sure its because I'm not looking hard enough but, can you create a way to invite the bot?

**Comment by janaSunrise** [comment]
I haven't worked on this much lately, mostly because this is now a huge project, and I'm the sole maintainer and contributor. Also - Discord.py is also deprecated. I plan to switch to one of it's fork in future, but currently, I would just give it some time, or probably would welcome contributions to make the codebase better and maintainable then start work with full energy.

**Comment by El-Vim55** [comment]
Alright, thanks
